server:
  port: 8080
  tomcat:
    relaxed-query-chars: "|"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health"
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      group:
        liveness:
          include: [ "livenessState", "readinessState" ]
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: "@project.artifactId@"
  ai:
    mcp:
      server:
        name: FHIR MCP Server
        version: 1.0.0
        instructions: "This server provides access to a FHIR RESTful API. You can use it to query FHIR resources, perform operations, and retrieve data in a structured format."
        enabled: true
        streamable-http:
          mcp-endpoint: /mcp/messages
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  flyway:
    enabled: false
    baseline-on-migrate: true
    fail-on-missing-locations: false
  datasource:
    url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 20
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false

hapi:
  fhir:
    openapi_enabled: true
    fhir_version: R4
    allow_external_references: true
    allow_external_valueset_expansion: true
    ig_runtime_upload_enabled: true

    terminology:
      valueset_preexpansion_mode: IGNORE
      valueset_expansion_mode: USE_EXPANSION_OPERATION
      valueset_membership_mode: USE_VALIDATE_CODE_OPERATION
      code_lookup_mode: USE_VALIDATE_CODE_OPERATION
      remote_terminology:
        - url: '${ONTO_SERVER_URL}'
          client_interceptor_beans:
            - terminologyInterceptor

    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*

    implementationguides:
      #ukcore:
      #  name: fhir.r4.ukcore.stu3.currentbuild
      #  version: 0.28.0-pre-release
      #  reloadExisting: false
      #  installMode: STORE_AND_INSTALL

    data:
      search_parameter_mode: USE_SEARCH_PARAMETERS
      terminology_parameter_mode: USE_VALUE_SET_URL
      profile_mode: DECLARED

    custom-bean-packages:
      - com.nhs
    custom-interceptor-classes:
      - com.nhs.TerminologyInterceptor

    cr:
      enabled: false
      caregaps:
        reporter: "default"
        section_author: "default"
